### PR TITLE
Dark and Light Mode Switch

### PR DESCRIPTION
**Pull request by Mupati**
This PR creates the switch which will be used to toggle between the dark mode and light mode. The functionality is yet to follow.

### CODE REVIEW

**Comment by Mupati** [comment]
@roughcoding I'm done with the light theme implementation. Your review is welcome.

**Comment by Mupati** [comment]
@roughcoding kindly clarify what you mean by the "The alteration of the shape of the images?". I think the remaining ones are clear

**Comment by roughcoding** [comment]
> @roughcoding kindly clarify what you mean by the "The alteration of the shape of the images?". I think the remaining ones are clear

@Mupati Will attach the screenshots along, hope it explains. I think it could be due to some global CSS rules affecting those images(Logo and repository image).

Screenshot of version, before theme-switch implementation.
Screenshot 2019-09-09 at 11 54 17 AM

Screenshot of the version after theme-switch.
Screenshot 2019-09-09 at 11 54 32 AM

**Comment by Mupati** [comment]
@roughcoding  I've submitted a PR for the requested changes

**Pull request merged**
